use_frameworks!

target 'InfnoteChain_Example' do
  pod 'InfnoteChain', :path => '../'

  target 'InfnoteChain_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
