platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'InfnoteChain_Example' do
  pod 'InfnoteChain', :path => '../'

  target 'InfnoteChain_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
